name: EnviroConcepts
favicon: null
layout_spectrum: 0.026659428607672453
typography_spectrum: 0.8453728903550655
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000700'
    - '#1c1f14'
    - '#f6fbff'
    - '#3f501d'
    - '#5e6f28'
  brandStrength: 0.9821237390860915
  lightness: 0.7966521468479186
  saturation: 0.7997063875664026
  rhythmicContrast: 0.771867462201044
purpose: []
