name: EnviroConcepts
favicon: null
layout_spectrum: 0.16578
typography_spectrum: 0.30517
title: EnviroConcepts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0e1a2a'
    - '#3a4153'
    - '#242b3d'
    - '#4b5264'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
